snd-soc-tas2559-objs := tas2559-core.o tas2559-regmap.o tas5766-regmap.o tas5782-regmap.o tas2559-codec.o tas2559-misc.o tiload.o
#snd-soc-tas5782-objs := tas5782m.o
snd-soc-tas5782-objs := tas5782m.o tas5782m-misc.o
obj-$(CONFIG_SND_SOC_TAS2559) += snd-soc-tas2559.o
obj-$(CONFIG_SND_SOC_TAS5782) += snd-soc-tas5782.o
